// Generated tools/list payload. Regenerate with scripts/gen_tools.py if
// you change the tool set (or edit carefully by hand and validate as JSON).
#pragma once

static const char kMcpToolsJson[] =
    "{\"tools\":[{\"name\":\"screenshot\",\"description\":\"Capture the current Switch screen as a JPEG image (128"
    "0x720). Returns the image directly so you can see what is on screen.\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{\"stack\":{\"type\":\"string\",\"enum\":[\"screenshot\",\"default\",\"lcd\",\"recording\",\"lastframe\""
    "],\"description\":\"Layer stack to capture. Default: screenshot (what the Capture button sees).\"}}}},{\""
    "name\":\"tap_buttons\",\"description\":\"Press and release controller buttons (synchronous). A virtual Pro"
    " Controller is attached automatically. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN"
    ", LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"buttons"
    "\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X,"
    " Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"How long to hold before releasing, in ms. Default 100, max 10000.\"}"
    ",\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screenshot taken "
    "after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"descrip"
    "tion\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"buttons"
    "\"]}},{\"name\":\"tap_sequence\",\"description\":\"Perform a sequence of button taps in one call, e.g. to na"
    "vigate menus. Each step presses its buttons, holds, releases, then waits before the next step. Butto"
    "n names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE"
    ".\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"taps\":{\"type\":\"array\",\"maxItems\":32,\"description\":\""
    "Sequence of taps (max 32).\",\"items\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\""
    ":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, M"
    "INUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":{\"type\":\"integer\",\"descri"
    "ption\":\"Hold time in ms. Default 100.\"},\"delayAfterMs\":{\"type\":\"integer\",\"description\":\"Pause after "
    "release in ms. Default 150.\"}},\"required\":[\"buttons\"]}},\"screenshot\":{\"type\":\"boolean\",\"description\""
    ":\"If true, the result also includes a screenshot taken after the input, saving a separate screenshot"
    " call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (le"
    "ts the UI settle). Default 250.\"}},\"required\":[\"taps\"]}},{\"name\":\"hold_buttons\",\"description\":\"Press"
    " buttons and keep them held until release_buttons or clear_input. Button names: A, B, X, Y, L, R, ZL"
    ", ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"obj"
    "ect\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act"
    " on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOM"
    "E, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a scre"
    "enshot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"inte"
    "ger\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}},\"requir"
    "ed\":[\"buttons\"]}},{\"name\":\"release_buttons\",\"description\":\"Release previously held buttons.\",\"inputS"
    "chema\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"descripti"
    "on\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, "
    "LSTICK, RSTICK, HOME, CAPTURE.\"},\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result a"
    "lso includes a screenshot taken after the input, saving a separate screenshot call.\"},\"screenshotDel"
    "ayMs\":{\"type\":\"integer\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Defa"
    "ult 250.\"}},\"required\":[\"buttons\"]}},{\"name\":\"set_stick\",\"description\":\"Set an analog stick position"
    ". x/y range -1.0..1.0 (y=1.0 is up). With durationMs the stick recenters afterwards; without it the "
    "position persists until changed or clear_input.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"side\""
    ":{\"type\":\"string\",\"enum\":[\"left\",\"right\"]},\"x\":{\"type\":\"number\"},\"y\":{\"type\":\"number\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"Hold time before recentering. Max 10000.\"},\"screenshot\":{\"type\":\"bo"
    "olean\",\"description\":\"If true, the result also includes a screenshot taken after the input, saving a"
    " separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer\",\"description\":\"Delay before that "
    "screenshot in ms (lets the UI settle). Default 250.\"}},\"required\":[\"side\"]}},{\"name\":\"clear_input\",\""
    "description\":\"Release all held buttons and recenter both sticks.\",\"inputSchema\":{\"type\":\"object\",\"pr"
    "operties\":{\"screenshot\":{\"type\":\"boolean\",\"description\":\"If true, the result also includes a screens"
    "hot taken after the input, saving a separate screenshot call.\"},\"screenshotDelayMs\":{\"type\":\"integer"
    "\",\"description\":\"Delay before that screenshot in ms (lets the UI settle). Default 250.\"}}}},{\"name\":"
    "\"status\",\"description\":\"Get server status: version, console firmware, virtual controller state, upti"
    "me.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"list_directory\",\"description\":\"List a"
    " directory on the SD card. Returns JSON with name/type/size/mtime per entry.\",\"inputSchema\":{\"type\":"
    "\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on the SD card, e.g. /sw"
    "itch/myapp/log.txt\"}},\"required\":[\"path\"]}},{\"name\":\"read_file\",\"description\":\"Read a text file from"
    " the SD card (logs, configs). Returns up to 32 KB per call; use offset/length to page through larger"
    " files. A negative offset reads from the end of the file (tail).\",\"inputSchema\":{\"type\":\"object\",\"pr"
    "operties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/l"
    "og.txt\"},\"offset\":{\"type\":\"integer\",\"description\":\"Byte offset; negative = from end of file.\"},\"leng"
    "th\":{\"type\":\"integer\",\"description\":\"Max bytes to read (capped at 32768).\"}},\"required\":[\"path\"]}},{"
    "\"name\":\"upload_file\",\"description\":\"Write a file to the SD card. content is base64-encoded and is st"
    "reamed to disk, so size is limited only by SD space - but large binaries are cheaper to deploy via t"
    "he raw HTTP API (curl -T file 'http://<ip>:<port>/files?path=...').\",\"inputSchema\":{\"type\":\"object\","
    "\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on the SD card, e.g. /switch/myap"
    "p/log.txt\"},\"content\":{\"type\":\"string\",\"description\":\"Base64-encoded file content.\"}},\"required\":[\"p"
    "ath\",\"content\"]}},{\"name\":\"delete_file\",\"description\":\"Delete a file or empty directory on the SD ca"
    "rd.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute pa"
    "th on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\"]}},{\"name\":\"create_token\",\"descr"
    "iption\":\"Create a new bearer token for the raw HTTP API (returned as text). Useful when a tool call "
    "is impractical, e.g. uploading large files with curl: pass it as an 'Authorization: Bearer <token>' "
    "header. The token is a long-lived credential for this console - do not store it outside the current "
    "task. Revoke by deleting its line from config/sys-autopilot/tokens.txt.\",\"inputSchema\":{\"type\":\"obje"
    "ct\",\"properties\":{}}},{\"name\":\"revoke_token\",\"description\":\"Revoke a bearer token previously issued "
    "via create_token or the OAuth login flow (removes it from tokens.txt). Use this to clean up tokens y"
    "ou created once they are no longer needed. Careful: revoking the token your own MCP connection uses "
    "will lock you out.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"token\":{\"type\":\"string\",\"descripti"
    "on\":\"The token to revoke.\"}},\"required\":[\"token\"]}},{\"name\":\"sleep\",\"description\":\"Put the console i"
    "nto sleep mode. WARNING: the server becomes unreachable immediately and CANNOT be woken remotely - a"
    " human must physically press a button on the console or a paired controller to wake it. Only use whe"
    "n explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"restart\",\"descript"
    "ion\":\"Reboot the console. WARNING: the server goes down immediately, and whether it returns without "
    "human help depends on the bootloader: setups that boot into a menu (e.g. Hekate without autoboot) re"
    "quire someone to manually re-launch the firmware. In-memory state (held buttons, virtual controller)"
    " is lost. Only use when explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"nam"
    "e\":\"power_off\",\"description\":\"Fully power off the console. WARNING: the server becomes permanently u"
    "nreachable - a human must physically press the power button to turn the console back on. Only use wh"
    "en explicitly asked to.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}}]}";
