// Generated tools/list payload. Regenerate with scripts/gen_tools.py if
// you change the tool set (or edit carefully by hand and validate as JSON).
#pragma once

static const char kMcpToolsJson[] =
    "{\"tools\":[{\"name\":\"screenshot\",\"description\":\"Capture the current Switch screen as a JPEG image (128"
    "0x720). Returns the image directly so you can see what is on screen.\",\"inputSchema\":{\"type\":\"object\""
    ",\"properties\":{\"stack\":{\"type\":\"string\",\"enum\":[\"screenshot\",\"default\",\"lcd\",\"recording\",\"lastframe\""
    "],\"description\":\"Layer stack to capture. Default: screenshot (what the Capture button sees).\"}}}},{\""
    "name\":\"tap_buttons\",\"description\":\"Press and release controller buttons (synchronous). A virtual Pro"
    " Controller is attached automatically. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN"
    ", LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"buttons"
    "\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X,"
    " Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":"
    "{\"type\":\"integer\",\"description\":\"How long to hold before releasing, in ms. Default 100, max 10000.\"}"
    "},\"required\":[\"buttons\"]}},{\"name\":\"tap_sequence\",\"description\":\"Perform a sequence of button taps i"
    "n one call, e.g. to navigate menus. Each step presses its buttons, holds, releases, then waits befor"
    "e the next step. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK,"
    " RSTICK, HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"taps\":{\"type\":\"array\",\"maxIte"
    "ms\":32,\"description\":\"Sequence of taps (max 32).\",\"items\":{\"type\":\"object\",\"properties\":{\"buttons\":{"
    "\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X, Y,"
    " L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"},\"durationMs\":{\"t"
    "ype\":\"integer\",\"description\":\"Hold time in ms. Default 100.\"},\"delayAfterMs\":{\"type\":\"integer\",\"desc"
    "ription\":\"Pause after release in ms. Default 150.\"}},\"required\":[\"buttons\"]}}},\"required\":[\"taps\"]}}"
    ",{\"name\":\"hold_buttons\",\"description\":\"Press buttons and keep them held until release_buttons or cle"
    "ar_input. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK"
    ", HOME, CAPTURE.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"buttons\":{\"type\":\"array\",\"items\":{\"t"
    "ype\":\"string\"},\"description\":\"Buttons to act on. Button names: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS"
    ", UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"}},\"required\":[\"buttons\"]}},{\"name\":\"release"
    "_buttons\",\"description\":\"Release previously held buttons.\",\"inputSchema\":{\"type\":\"object\",\"propertie"
    "s\":{\"buttons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"description\":\"Buttons to act on. Button nam"
    "es: A, B, X, Y, L, R, ZL, ZR, PLUS, MINUS, UP, DOWN, LEFT, RIGHT, LSTICK, RSTICK, HOME, CAPTURE.\"}},"
    "\"required\":[\"buttons\"]}},{\"name\":\"set_stick\",\"description\":\"Set an analog stick position. x/y range "
    "-1.0..1.0 (y=1.0 is up). With durationMs the stick recenters afterwards; without it the position per"
    "sists until changed or clear_input.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"side\":{\"type\":\"st"
    "ring\",\"enum\":[\"left\",\"right\"]},\"x\":{\"type\":\"number\"},\"y\":{\"type\":\"number\"},\"durationMs\":{\"type\":\"int"
    "eger\",\"description\":\"Hold time before recentering. Max 10000.\"}},\"required\":[\"side\"]}},{\"name\":\"clea"
    "r_input\",\"description\":\"Release all held buttons and recenter both sticks.\",\"inputSchema\":{\"type\":\"o"
    "bject\",\"properties\":{}}},{\"name\":\"status\",\"description\":\"Get server status: version, console firmwar"
    "e, virtual controller state, uptime.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{}}},{\"name\":\"list"
    "_directory\",\"description\":\"List a directory on the SD card. Returns JSON with name/type/size/mtime p"
    "er entry.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absol"
    "ute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\"]}},{\"name\":\"read_file\",\"de"
    "scription\":\"Read a text file from the SD card (logs, configs). Returns up to 32 KB per call; use off"
    "set/length to page through larger files. A negative offset reads from the end of the file (tail).\",\""
    "inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path on "
    "the SD card, e.g. /switch/myapp/log.txt\"},\"offset\":{\"type\":\"integer\",\"description\":\"Byte offset; neg"
    "ative = from end of file.\"},\"length\":{\"type\":\"integer\",\"description\":\"Max bytes to read (capped at 3"
    "2768).\"}},\"required\":[\"path\"]}},{\"name\":\"upload_file\",\"description\":\"Write a file to the SD card. co"
    "ntent is base64-encoded and is streamed to disk, so size is limited only by SD space - but large bin"
    "aries are cheaper to deploy via the raw HTTP API (curl -T file 'http://<ip>:<port>/files?path=...')."
    "\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute path "
    "on the SD card, e.g. /switch/myapp/log.txt\"},\"content\":{\"type\":\"string\",\"description\":\"Base64-encode"
    "d file content.\"}},\"required\":[\"path\",\"content\"]}},{\"name\":\"delete_file\",\"description\":\"Delete a fil"
    "e or empty directory on the SD card.\",\"inputSchema\":{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"s"
    "tring\",\"description\":\"Absolute path on the SD card, e.g. /switch/myapp/log.txt\"}},\"required\":[\"path\""
    "]}}]}";
